version: '3.8'

services:
  smartoffice-web:
    image: ${ACR_LOGIN_SERVER}/smartoffice-web:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - POSTGRES_HOST=db-postgres
      - POSTGRES_USER=admin_postgres
      - POSTGRES_PASSWORD=secret_postgres
      - POSTGRES_DB=smartoffice
      - MONGO_URI=mongodb://db-mongo:27017/smartoffice_iot
    depends_on:
      db-postgres:
        condition: service_healthy
      db-mongo:
        condition: service_healthy

  db-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin_postgres
      - POSTGRES_PASSWORD=secret_postgres
      - POSTGRES_DB=smartoffice
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-mongo:
    image: mongo:6-alpine
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
